server:
  port: 9000
spring:
  application:
    name: authorizationserver
  datasource:
    url: jdbc:postgresql://localhost:5433/instagenius
    username: admin
    password: admin
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
logging:
  level:
    org.springframework.security: trace

