server:
  port: 9000
spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          test-client:
#            registration:
#              client-id: test-client-id
#              client-secret: test-client-secret
#              client-authentication-methods:
#                - client_secret_basic
#              authorization-grant-types:
#                - client_credentials
#                - refresh_token
#                - authorization_code
#              redirect-uris:
#                - http://127.0.0.1:8082/login/oauth2/code/test-client
#              scopes:
#                - user.read
#                - user.write
#                - openid
#            require-authorization-consent: true
  application:
    name: authorizationserver
logging:
  level:
    org.springframework.security: trace

