server:
  port: 8082
spring:
  application:
    name: CloudGateway
  security:
    oauth2:
      client:
        registration:
          test-client:
            provider: spring
            client-id: test-client-id
            client-secret: test-client-secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - user.read
        provider:
          spring:
            issuer-uri: http://localhost:9000
